### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by emlun** [maiflai/gradle-scalatest#16]
I've tried this:

`build.gradle`

    plugins {
      id "com.github.maiflai.scalatest" version "0.6-5-g9065d91"
    }
    apply plugin: 'scala'

    task wrapper(type: Wrapper) {
      gradleVersion = '2.2'
    }

    repositories {
      mavenCentral()
    }

    dependencies {
      compile 'org.scala-lang:scala-library:2.+'
      testCompile 'org.scalatest:scalatest_2.11:2.+'
    }

`src/main/scala/Foo.scala`

    object Foo {
      def getZero() = 0
    }

`src/test/scala/Test.scala`

    import org.scalatest._

    class FooSpec extends FunSpec with Matchers {
      describe("The Foo object") {
        describe("has a getZero method which") {
          it("returns 0") {
            Foo.getZero should be (0)
          }
        }
      }
    }

But when I run `$ gradle test`, a `java.lang.NoClassDefFoundError: org/pegdown/PegDownProcessor` is thrown. What am I doing wrong? [Here][repo] is a repo with the test project, see the README for more details.

[repo]: https://github.com/emlun/gradle-scalatest-missing-dependency

**Comment by maiflai** [comment]
Sorry, the previous version of the README included this instruction:

```groovy
dependencies {		
   compile 'org.scala-lang:scala-library:2.10.1'		
   testCompile 'org.scalatest:scalatest_2.10:2.0'		
   testRuntime 'org.pegdown:pegdown:1.1.0'		
}
```
scalatest requires pegdown to write HTML reports.

I'll update the README accordingly.

**Comment by emlun** [comment]
Thanks for the quick reply! Yeah, that makes sense. I looked through both the ScalaTest jars (one downloaded manually and one downloaded by Gradle) and the plugin jar and couldn't find any PegDown files anywhere, and I'd never heard of the library before, so I was a bit confused over why it would work with the JUnit runner but not the plugin runner. Thanks!
