### ISSUE TITLE
Expose option to run specific test by name and specific suite by name

### ISSUE THREAD

**Issue by jfiore-ibm** [maiflai/gradle-scalatest#21]
The ScalaTest runner has the ability to run a specific test by name (-t option) and a specific suite (-s option)

see: http://doc.scalatest.org/2.1.1/index.html#org.scalatest.tools.Runner$

It is useful to be able to use these when working with a specific test (so as to not have to run all tests).

Would it be possible to expose these options via the gradle plugin with some convention properties?

Alternatively, could you expose a convention property that lets the caller specify all of the args to be sent to ScalaTest Runner?
Using that property would set all of the args.
i.e. in ScalaTestAction, something like:
if(userSpecifiedArgs) {
  javaExecHandleBuilder.setArgs(userSpecifiedArgs)
}
else {
  javaExecHandleBuilder.setArgs(getArgs(t))
}

**Comment by maiflai** [comment]
Sorry for the delay.

I looked at running a single test before, but it was around the time that `test.single` was being deprecated. I'll take a look at the now standard interpretation of `--tests` and see what I can do.

Personally I prefer to run single tests in the IDE; if I need to run a single test it is generally because I need a debugger.

I do have the occasional single test which needs to be run outside of the regular test run, and in that case I've tended to explicitly configure a `JavaExec` task because the arguments are simple. Otherwise I tend to use scalatest tags to group my tests into categories such as Integration and Acceptance, and then configure additional test tasks to run them.

Do those approaches help you in the meantime?

Thanks,
Stu

**Comment by jfiore-ibm** [comment]
Stu, 
Thanks for the suggested workarounds. I can try the JavaExec approach in the meantime.

We generally run single tests from the IDE, but certain tests can only be run from gradle (since we start services and such as part of the pre-test build tasks).

**Comment by maiflai** [comment]
Ah, yes - in the case of the service-dependent tests we tend to bind them together in a Suite and then manage the services as part of the before|after all in the Suite.

We can then run the tests in the IDE, and get full debug of the service and the test, or run the individual tests against an external service.

I agree it might be helpful to be able to define a test task for a single test; there's not much work to use `JavaExec` but it does become repetitive.

**Comment by maiflai** [comment]
I added support for gradle test filtering into 0.8 (`--tests`) - I realise it's not quite the same as specifying an explicit class but it might go some way towards running a single test case?

**Comment by jfiore-ibm** [comment]
I will try the new release out today hopefully. I imagine that will suit our needs.
And thanks for the suggestion about running the services in before/after suite.

**Comment by jfiore-ibm** [comment]
Stu,

I had a chance to check it out (sorry for the delay).

I would say that it meets most of our needs, but it doesn't allow you to run a particular Suite.
I think to fully support what we need, we would need to be able to specify tests by using the -s option also.

Let me know if you think that might be a possibility.

Thanks.

**Comment by maiflai** [comment]
I thought that you might be able to simply pass the Suite name in?

My main concern is around the configuration of reports; the underlying Test task incrementally delivers the XML reports into **_build_/test-results** but overwrites the HTML report in **_build_/reports/tests** . 

Do you plan to run multiple suites in a single build?

**Comment by jfiore-ibm** [comment]
Currently, if we run multiple ScalaTest Test tasks in a single build, we set the report directory differently so that they don't get overwritten.

**Comment by jfiore-ibm** [comment]
Also, with regard to trying to pass the Suite name in:
Yes we did try that and it didn't appear to work. The problem seems to be that the -s flag applies to the test name, and unfortunately, the suite class name isn't a part of the test name (this is particularly true of FeatureSpec).

**Comment by maiflai** [comment]
Hi,

I've uploaded a preview of the 0.9 build - please could you test it? You'll need to add the following to your project, replacing any other declaration of the scalatest plugin.

```groovy
buildscript {
    repositories {
        maven { url 'https://oss.sonatype.org/service/local/repositories/comgithubmaiflai-1018/content'}
    }
    dependencies {
        classpath 'com.github.maiflai:gradle-scalatest:0.9'
    }
}
```

You can then add suite tasks in the following manner:

```groovy
task userStories(type: Test) {
    suite 'com.example.UserStories'
    // suites 'a.Spec', 'b.Spec', 'etc'
}
```

Thanks,
Stu

**Comment by jfiore-ibm** [comment]
Sorry for the delay again Stu.

I got a chance to test your preview build. 
That works great.

That allows us to run an entire Feature in a FeatureSpec (using the filter.includeTestsMatching in the last release).
And it allows us to run a specific Suite or set of Suites.

Please go ahead and release it.

And thank you again for being so responsive and knocking this out so quickly.

**Comment by maiflai** [comment]
No worries - that should be available on maven central and bintray shortly.

Thanks,
Stu
