### ISSUE TITLE
IllegalArgumentException: Use of I was deprecated in ScalaTest 1.0

### ISSUE THREAD

**Issue by kevinstembridge** [maiflai/gradle-scalatest#23]
Hi,

I'm using version 2.0.M5b of scalatest and I'm getting the following error:

IllegalArgumentException: Use of I was deprecated in ScalaTest 1.0 and removed in 1.5.

Here are the latest supported config options:
http://www.scalatest.org/user_guide/using_scalatest_with_sbt

Let me know if you need any more info.

Cheers,

Kevin

**Comment by maiflai** [comment]
Hi,

That's strange - I can see that we supply the argument `-oID`, but this seems to work with several versions after 2.0. It may be that the argument is now silently ignored?

Is there a reason that you're not using a later version of scalatest itself? I'm not aware of any issues with the current release, but I do recall some teething trouble between 2.0.M5b and 2.0.

Thanks,
Stu

**Comment by maiflai** [comment]
Hi,

I've published https://github.com/maiflai/gradle-scalatest/releases/tag/0.10 which should solve the issue (if you haven't already moved to a full 2.x version of scalatest).

Please can I close this issue?

Thanks,
Stu

**Comment by kevinstembridge** [comment]
Hi Stu,

I must apologise, I'm no longer using this plugin.

I appreciate the follow up though.

Many thanks,
Kevin

**Comment by maiflai** [comment]
No worries, thanks for raising the issue.
