### ISSUE TITLE
Filtering doesn't appear to work

### ISSUE THREAD

**Issue by sdavids13** [maiflai/gradle-scalatest#28]
I have attempted to filter scala tests a couple of ways without success:

```
task testSection1(type: Test) {
    filter{
        includeTestsMatching '*.BasicRddManipulationTest'
    }
}
```

`./gradlew :word-count:clean :word-count:testSection1`

`./gradlew :word-count:clean :word-count:test --tests BasicRddManipulationTest`
`./gradlew :word-count:clean :word-count:test --tests *.BasicRddManipulationTest`

None of these combinations seem to do the trick resulting in no tests being run via version `0.11`. I went back to version `0.7` and tried the task filtering, it did run a single test, but unfortunately it seemed to be random which test it would actually run (not matching the name). Here is my build script:

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.github.maiflai:gradle-scalatest:0.11"
        classpath "com.netflix.nebula:gradle-extra-configurations-plugin:3.0.3"
    }
}

subprojects {
    apply plugin: 'scala'
    apply plugin: 'com.github.maiflai.scalatest'
    apply plugin: "nebula.provided-base"

    group 'com.bti360'

    repositories {
        mavenCentral()
    }

    ext {
        sparkVersion = '1.4.1'
        scalaVersion = '2.11'
    }

    dependencies {
        provided "org.apache.spark:spark-core_${scalaVersion}:${sparkVersion}"
        provided "org.scala-lang:scala-library:${scalaVersion}.+"

        testCompile "com.holdenkarau:spark-testing-base_${scalaVersion}:${sparkVersion}_0.3.1"
        testCompile "org.scalatest:scalatest_${scalaVersion}:2+"
    }

    test {
        maxParallelForks = 1
    }

    tasks.withType(ScalaCompile) {
        scalaCompileOptions.useAnt = false
    }

    //Create ubjerJar/fatJar/shadowJar excluding provided dependencies
    jar {
        from { (configurations.runtime - configurations.provided).collect { it.isDirectory() ? it : zipTree(it) } }
        exclude('META-INF/INDEX.LIST', 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA')
    }
}
```

**Comment by maiflai** [comment]
Hi,

The filter is mapped to ScalaTest's `-z` parameter; I think this only matches words in the test specification (rather than the name of the test class itself).

Can you provide the source code to the test you wish to run please? 

Thanks,
Stu.

**Comment by sdavids13** [comment]
Here is an example test:
```
package com.bti360.spark101

import com.holdenkarau.spark.testing.SharedSparkContext
import org.scalatest.{Matchers, FunSuite}

class FooTest extends FunSuite with Matchers with SharedSparkContext {
  test("pluralize all words in the rdd") {
    val input = sc.parallelize("The quick red fox jumped over the lazy brown dog".split(' '))
    val expected = "Thes quicks reds foxs jumpeds overs thes lazys browns dogs".split(' ')

    input.map(_ + 's').collect().toList should contain theSameElementsAs expected
  }

  test("filter THE from rdd") {
    val input = sc.parallelize("The quick red fox jumped over the lazy brown dog".split(' '))
    val expected = "quick red fox jumped over lazy brown dog".split(' ')

    input.filter(!_.equalsIgnoreCase("the")).collect().toList should contain theSameElementsAs expected
  }
}
```

So, for this example the following don't work: 
  * `./gradlew :word-count:test --tests .*FooTest`
  * `./gradlew :word-count:test --tests *FooTest*`

But this does: `./gradlew :word-count:test --tests pluralize` but unfortunately that also matches other tests I have and ignores the `filter THE from rdd` test.

I ripped out the scala-test plugin and added the JUnit runner via `@RunWith(classOf[JUnitRunner])` which allows `./gradlew :word-count:test --tests *.FooTest` to work as as expected - executing the two tests in the class

Perhaps this is just confusing because the same semantics are being used for something that is just different..

**Comment by maiflai** [comment]
Thanks for the example - yes, this uses the ScalaTest semantics which aren't as helpful as the Gradle ones.

I think this isn't something that's particularly well supported by ScalaTest clients - IntelliJ has similar issues coping with the various forms of test declarations.

My usual way of working is to use tags to categorise tests for separate running. If I need to re-run a particular test then I'm usually debugging a failure in an IDE. I also deliberately avoid using the `it` keyword.

**Comment by lbergelson** [comment]
@maiflai Hi, we've run into this problem too.  We've been using your your plugin to allow us to run add scala tests to project that has primarily java code and tests.  

Is there any possibility of changing the behavior so it matches gradle's `--test` behavior?  As far as I can see from this discussion isn't any way to match java tests using the overridden `--test` behavior, and we have thousands of tests so manually labelling them all in unique groups is impractical.

**Comment by maiflai** [comment]
My concern was related to completeness; ScalaTest itself doesn't provide such a simple generic test discovery option, so it's not possible to accurately match Gradle.

As a guide, the ScalaTest runner supports:

* -w <wildcard package>
* -s <suite class name>
* -q <suffixes>
* -z <test name substring>
* -t <test name>

This plugin maps --tests to -z <test name substring>, which can be appropriate if you use the "it should" form of testing. 

It may be that for your use the -q <suffix> would be sufficient, as it would allow requesting a test class without specifying the full classname.

Ideally the upstream ScalaTest runner would support the wildcard form directly.

**Comment by maiflai** [comment]
Hi,

I've tried to address this in 0.18, please could you see if it helps?

Thanks,
Stu

**Comment by maiflai** [comment]
Closing, no response
