### ISSUE TITLE
scalatest in sonar

### ISSUE THREAD

**Issue by kknd22** [maiflai/gradle-scalatest#29]
sonar seems to have problem to read the output result from scalatest `$buildDir/test-results`.
Basically, the sonar reports are missing for `Unit Test Success` `Failures`  `Tests Count` and `Execution Time`. For either scalatest on testing java code or scala code.
While Scoverage has all the correct information.

p.s
The plugin I have for sonar are: 

```
- Scalastyle 
- Scoverage
```

The gradle plugins are:

```
- "org.sonarqube.gradle:gradle-sonarqube-plugin:1.1"
- 'org.github.ngbinh.scalastyle:gradle-scalastyle-plugin_2.11:0.7.2'
- 'org.scoverage:gradle-scoverage:1.0.9'
- 'com.github.maiflai:gradle-scalatest:0.10'
```

 Am I missing some plugins and mis-configued any thing?

Thanks
-Chris L.

**Comment by maiflai** [comment]
Hi,

I cloned https://github.com/kknd22/sonar-scala-demo and ran it against a local installation of sonarqube-5.1 with scalastyle and scoverage plugins installed.

I added
```
property 'sonar.verbose', 'true'
```

`sonar-java-scalatest-jacoco` reports the following:

>INFO  - Sensor SurefireSensor
INFO  - parsing /Users/stu/Documents/Eclipse/sonar-scala-demo/sonar-java-scalatest-jacoco/build/test-results
DEBUG - Class not found in resource cache : com.example.integration.TestPrimeNumberScalaOnJava
WARN  - Resource not found: com.example.integration.TestPrimeNumberScalaOnJava

and

`sonar-scala-scalatest-scoverage` doesn't register the `SurefireSensor` at all.

>INFO  - Quality profile for scala: Scalastyle
DEBUG - Sensors : Lines Sensor (wrapped) -> QProfileSensor -> InitialOpenIssuesSensor -> ProjectLinksSensor -> VersionEventsSensor -> com.ncredinburgh.sonar.scalastyle.ScalastyleSensor@6eecd8ca -> ScoverageSensor -> SCM Sensor (wrapped) -> CPD Sensor (wrapped)

I don't know enough about sonarqube to understand this yet, but I think these are not problems with either the scoverage or the scalatest plugin.

I'll see if I can figure out why 
* the java source file is not found
* the surefire sensor is not loaded

But you may be better off taking the debug logs to the sonarqube team?

Thanks,
Stu

**Comment by maiflai** [comment]
On reviewing the SurefireSensor it uses a `JavaResourceLocator` which isn't picking up the Scala source files. You can demonstrate this by adding a Scala JUnit test.

I think we need a specific ScalaTestSensor to deal with JUnit-style XML and Scala source files.

**Comment by maiflai** [comment]
I've pushed a Sonar 5.1 plugin to https://github.com/maiflai/sonar-scalatest - would you be able to test it please?

```
mvn package
```

and then copy the resulting jar file into the Sonar `extensions/plugins` directory.

**Comment by kknd22** [comment]
I will give it a try today or tomorrow. Thanks Stu

**Comment by maiflai** [comment]
Closing old issue
