### ISSUE TITLE
"error=206, The filename or extension is too long" error on Windows

### ISSUE THREAD

**Issue by Javaru** [maiflai/gradle-scalatest#30]
The MS Windows command line [CreateProcess function has a limit of 32,767 characters](https://blogs.msdn.microsoft.com/oldnewthing/20031210-00/?p=41553). (The CMD.EXE command processor has a 8192 character command line length limit.)  The scalatest plug-in can create a command line exceeding the 32K limit due to a lengthy value for the "-cp" argument when there are a large number of dependencies. (We had a classpath value length of 40,529 characters). This issue does not occur with Java tests as the Gradle test plug-in is handling the classpath differently.

Too long of a command line results in the error:
`java.io.IOException: CreateProcess error=206, The filename or extension is too long`

The Maven Surefrie (testing) plugin had to deal with this issue -- see [discussion here](http://maven.apache.org/surefire/maven-surefire-plugin/examples/class-loading.html) -- as has other gradle plug-ins such as the [gradle-vaadin-plugin](https://github.com/johndevs/gradle-vaadin-plugin/issues/92), the [FindBugs plugin](https://issues.gradle.org/browse/GRADLE-2167), the [application plugin](https://issues.gradle.org/browse/GRADLE-2992), and others.

The surefire discussion has some good information on possible solutions. In my borwsing, it appears most Gradle plug-ins are solving this issue via a manifest only jar that has a 'Class-Path' entry with all the JARs to use.

**Comment by maiflai** [comment]
I think this could better be solved by the `JavaExec` task; otherwise as you show, every user of it has to deal with this problem. It is responsible for creating the invalid command line.

In my personal projects I've worked around this using the `CLASSPATH` environment variable. However, this is very old behaviour and I'm not sure how portable it is across different JVM implementations.

**Comment by maiflai** [comment]
Potential workaround (as per https://github.com/maiflai/gradle-scalatest/issues/42)

```groovy
test {
  doFirst {
    def cp = CollectionUtils.join(File.pathSeparator, classpath.getFiles())
    environment 'CLASSPATH', cp
    classpath = classpath.filter { false }
  }
}
```

**Comment by yasin3061** [comment]
Try https://github.com/viswaramamoorthy/gradle-util-plugins

**Comment by chandiprasad** [comment]
@yasin3061 : this plugin worked for me ! Thanks !

**Comment by maiflai** [comment]
Gradle 6 now supports this via a manifest jar

**Comment by Hakem22** [comment]
@yasin3061  it works for me too! thanks.

**Comment by patnaiksangeeta88** [comment]
@yasin3061 Thanks...It worked
