### ISSUE TITLE
useAnt is deprecated

### ISSUE THREAD

**Issue by djmittens** [maiflai/gradle-scalatest#31]
I am using gradle 2.12 and it seems like some functionality is going away.

```
:compileTestScala
useAnt has been deprecated and is scheduled to be removed in Gradle 3.0. The Ant-Based Scala compiler is deprecated, please see https://docs.gradle.org/current/userguide/scala_plugin.html.
fork has been deprecated and is scheduled to be removed in Gradle 3.0. The fork option for the scala compiler is deprecated, please see https://docs.gradle.org/current/userguide/scala_plugin.html.
```

**Comment by maiflai** [comment]
I don't think the scalatest plugin has any opinion on using Ant to compile source code.

The documentation suggests that the Zinc compiler is now the default for the scala plugin.

Please can you share your source files?

**Comment by djmittens** [comment]
```
// Apply the java plugin to add support for Java
apply plugin: 'scala'
apply plugin: 'idea'

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.github.maiflai:gradle-scalatest:0.11"
    }
}

apply plugin: "com.github.maiflai.scalatest"

// In this section you declare where to find the dependencies of your project
repositories {
    mavenLocal()
    // Use 'jcenter' for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

// In this section you declare the dependencies for your production and test code
dependencies {
    compile 'org.scala-lang:scala-library:2.11.8'

    compile 'com.typesafe.akka:akka-actor_2.11:2.4.2'
    compile 'com.typesafe.akka:akka-stream_2.11:2.4.2'

    compile 'org.slf4j:slf4j-api:1.7.18'
    compile 'com.typesafe.akka:akka-slf4j_2.11:2.4.2'


    // Declare the dependency for your favourite test framework you want to use in your tests.
    // TestNG is also supported by the Gradle Test task. Just change the
    // testCompile dependency to testCompile 'org.testng:testng:6.8.1' and add
    // 'test.useTestNG()' to your build script.
    testCompile 'org.scalatest:scalatest_2.11:2+'
    testRuntime 'org.pegdown:pegdown:1.1.0'
}
```

**Comment by maiflai** [comment]
Interesting - I'll take a look at the Gradle source code later. I suspect that they may have deprecated the Ant compiler yet not made Zinc the default.

**Comment by radimk** [comment]
Yes, they did - https://docs.gradle.org/current/release-notes#scala-zinc-compiler-and-forked-compilation-on-by-default

**Comment by maiflai** [comment]
https://github.com/gradle/gradle/commit/65e762acdc15eaf942377d1fa95cec3021b95e20 suggests that they deliberately added the deprecation warning to the getter.

However, I think this getter is always called, and this warning is therefore always displayed (even if you are using the default value which leads to non-deprecated behaviour).

I'm not sure the getter needs this notification; I think the setter was sufficient. I'll check with them to understand the reasoning.

**Comment by skate056** [comment]
I have the same issue. I would like to get rid of the message and the noise in the build.

**Comment by maiflai** [comment]
Please can I close this issue? It seems to have been resolved in the latest Gradle release.

**Comment by maiflai** [comment]
Closing without response
