### ISSUE TITLE
Method isColorOutput was removed in Gradle 3

### ISSUE THREAD

**Issue by ashlineldridge** [maiflai/gradle-scalatest#37]
The plugin is currently (version 0.13) unusable with Gradle 3. The colour output API was deprecated in late Gradle 2.x and removed in Gradle 3. The error I receive in Gradle 3 is:

`No signature of method: org.gradle.StartParameter.isColorOutput() is applicable for argument types: () values: []`

**Comment by maiflai** [comment]
Hi - yes, I had spotted this and committed a fix. However, my automated tests suggest there might be a problem when interacting with Jacoco, so I've not yet published it yet.

Hopefully I'll get some time before the weekend to look closer.

Sorry,
Stu

**Comment by ashlineldridge** [comment]
No probs at all. Just thought I'd let you know. Thanks for the useful plugin!

**Comment by maiflai** [comment]
I've published 0.14 which should fix this - please could you have a look?

Thanks,
Stu

**Comment by ashlineldridge** [comment]
Thanks, Stu. Just checked 0.14 and it works with Gradle 3. Thanks!

**Comment by maiflai** [comment]
No worries, thanks for the input
