### ISSUE TITLE
 test.afterSuite was never invoked for scalatest test against scala code

### ISSUE THREAD

**Issue by kknd22** [maiflai/gradle-scalatest#40]
In multi gradle project case, we need to have scalatest to continue to run for all subprojects even some tests fail and be able to fail the overall build at the end.

We have implemented the following gradle script to capture junit test against java and using junit runner for using scalatest to test java code using (@RunWith(classOf[JUnitRunner]). Everything works great except using scalatest to test scala code. 

After debugging the issue, I discovered that  `test.afterSuite` were never be invoked in testing scala case, (works when testing java) . Do you know the cause and a way to make it work?  Thanks

-Chris L

```
rootProject.ext.testFailureCount = 0
task checkForDeferredTestFailure() << {
    if (rootProject.testFailureCount) {
        throw new Exception("There were ${testFailureCount} test failures.")
    }
}
gradle.startParameter.setTaskNames (gradle.startParameter.taskNames << ":checkForDeferredTestFailure")

gradle.taskGraph.whenReady { taskGraph ->
    taskGraph.allTasks.each { Task t ->
        if (t instanceof org.gradle.api.tasks.testing.Test) {
            def test = (Test) t
            test.ignoreFailures = true
            test.afterSuite { td, tr ->
                 // ----------------------------------------------------
                // -- it never comes in here when testing scala code, but file when testing java code
                 // ----------------------------------------------------
                if (td.getParent() == null) {
                    rootProject.testFailureCount += tr.getFailedTestCount()
                }
            }
        }
    }
}


```

**Comment by maiflai** [comment]
Have you tried adding `--continue` (https://discuss.gradle.org/t/new-feature-continue-execution-on-task-failure/7604) to the command line?

**Comment by maiflai** [comment]
I think what is probably happening is that you are only applying this plugin to the Scala projects.

This plugin replaces the Gradle JUnit implementation, and so will never invoke the `afterSuite` closure in those Scala projects.

In the other Java projects the closure is doing what you want.

I think the easiest way to achieve the aim of running all tests is to remove the implementation above and to pass `--continue` to Gradle on the command line. 

It should collect all the failed tasks together and report them at the end - could you try it and let me know?

Thanks,
Stu

**Comment by kknd22** [comment]
Stu,
  Thanks for the quick response. I am aware of  `--continue` option and it does work for **any** task failure. The requirement for us is to **only** continue on test failure not on all other task failures (so we still can have the full sonar report).
  I was looking at  the scalatest source code to handle the failure [ScalaTestAction](https://github.com/maiflai/gradle-scalatest/blob/master/src/main/groovy/com/github/maiflai/ScalaTestAction.groovy#L47) is there some way to make the callback on `afterSuite()` to occure like other task tasks?  More curious why the callback did not happen...
Thanks
-Chris

**Comment by kknd22** [comment]
btw, we did apply this plugin to both java and scala project - regardless what the main source is, both cases, all tests code are written with scalatest. The only difference is that to  test java code we add annotation `@RunWith(classOf[JUnitRunner]` for the scalatest spec such that jacoco can collecting code coverage information vs using scoverage when testing scala main source code

**Comment by maiflai** [comment]
My understanding (although somewhat old) is that `@RunWith(classOf[JUnitRunner]` allows JUnit to run ScalaTest tests.

i.e. you would use that if you wanted to **avoid** using this plugin.

It allows a standard Gradle `Test` task to execute your tests. However, it requires that each class has the annotation. I wrote this plugin specifically to avoid missed tests. 

This plugin does not use the Gradle testing framework, but it does try to provide a simple shim between Gradle and ScalaTest. It does not try to emit framework events to the `TestListener` and therefore `afterSuite` will not be called.

Perhaps you could share the build that you're looking at and I could suggest alternatives?

Thanks,
Stu

**Comment by kknd22** [comment]
Thanks Stu. After further discussion with the requirement folks, it seems `--continue` will satisfy our immediate needs. Considering the natural of this plugin provide *simple shim* approach, I will close this issue. 

Thanks
-Chris L

**Comment by maiflai** [comment]
No worries - thanks for the feedback. For what it's worth I have looked several times at creating a plugin with full support, but it's quite an involved piece of work and the benefit seems slim for my use cases. 

Good luck,
Stu

**Comment by kknd22** [comment]
It looks like that we still need a work around for this. 
To clarify the requirement: in the multi-projects for `gradle sonar`, we need to continue gradle tasks (sonar) even when some `test` tasks have already failed. Moreover, we need to mark the final build as failure after all test and sonar tasks.
 
Tried with the following approaches, when there are test failures:

1.  use `--continue`. This does allow to run all `test` tasks but then stopped and will **NOT** run sonar.
2. use `--continue` with ` test.ignoreFailures = true`. This does allow run everything including all tests and sonar, with the final build result is considered **successful**. However, it failed to mark the final build result as a **failure**.
3. use the code from the  original post. It achieves the result that we want (2. with the final build result as failure), however only for all **none** scalatests. Any of the scalatest failure will **not* trigger  rootProject.testFailureCount++. Such that in this case,  make the the build result wrongfully **successful**

The thought is that if gradle-scalatest can provide a callback or set a flag to indicate there are failure(s) during the test  then we can modify the code **3** to fail the overall build when any of the scalatest failure.

Any thoughts or suggestions?
Thanks
-Chris L.

**Comment by maiflai** [comment]
Interesting - how are you dealing with the build failure?

By default TeamCity will mark the build as failed when it detects test failures, so it's not strictly necessary for Gradle to exit with a non-zero status (which is one of the effects of throwing an `Exception` within a `Task`).

**Comment by maiflai** [comment]
closing old issue
