### ISSUE TITLE
Plugin with id 'com.github.maiflai.scalatest' not found

### ISSUE THREAD

**Issue by tiny-cababge** [maiflai/gradle-scalatest#41]
`buildscript { //For the plugins
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven {
            url "http://nexus.nephila.com/nexus/content/groups/public"
        }
    }
    dependencies {
        classpath 'com.github.rholder:gradle-one-jar:1.0.4'
        classpath 'com.bmuschko:gradle-nexus-plugin:2.3.1'
        classpath "gradle.plugin.com.github.maiflai:gradle-scalatest:0.14"
    }
}

apply plugin: 'com.github.maiflai.scalatest'`

`C:\Git_Workspace\Weather\weather.marketdata>gradlew -version

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Windows 7 6.1 amd64`

**Comment by maiflai** [comment]
Sorry, I'm unable to reproduce the error in the title with the build file above.

I see the following in my build log:

> Starting a Gradle Daemon (subsequent builds will be faster)
Download https://plugins.gradle.org/m2/com/github/rholder/gradle-one-jar/1.0.4/gradle-one-jar-1.0.4.pom
Download https://plugins.gradle.org/m2/com/bmuschko/gradle-nexus-plugin/2.3.1/gradle-nexus-plugin-2.3.1.pom
Download https://plugins.gradle.org/m2/gradle/plugin/com/github/maiflai/gradle-scalatest/0.14/gradle-scalatest-0.14.pom
Download https://plugins.gradle.org/m2/com/github/rholder/gradle-one-jar/1.0.4/gradle-one-jar-1.0.4.jar
Download https://plugins.gradle.org/m2/com/bmuschko/gradle-nexus-plugin/2.3.1/gradle-nexus-plugin-2.3.1.jar
Download https://plugins.gradle.org/m2/gradle/plugin/com/github/maiflai/gradle-scalatest/0.14/gradle-scalatest-0.14.jar

Please could you provide the build output?

Thanks,
Stu

**Comment by maiflai** [comment]
I'll close this tomorrow if no further feedback is provided.

Thanks,
Stu

**Comment by tiny-cababge** [comment]
Yea sorry, issue with our nexus. Sorry for wasting your time.
