### ISSUE TITLE
Up-to-date checks not running

### ISSUE THREAD

**Issue by yissachar** [maiflai/gradle-scalatest#45]
If i run `gradle test` twice in a row, without changing anything else in between, the tests are run twice.

I would expect this to use gradle up-to-date checks to prevent this from happening.

**Comment by maiflai** [comment]
It should - please could you provide a sample project which reproduces the issue, or a full debug log?

**Comment by yissachar** [comment]
Looks like this one is on me - I had a test that was sneakily writing a file to the build dir which caused the up-to-date checks to fail. Sorry!

**Comment by maiflai** [comment]
No worries, glad it's resolved.
