### ISSUE TITLE
java.lang.IncompatibleClassChangeError with cxf-rt-frontend-jaxws

### ISSUE THREAD

**Issue by kknd22** [maiflai/gradle-scalatest#46]
Stu,
  I am running into a very weird issue, illustrated a simple project create in github:
[gradle-scalatest-demo](https://github.com/kknd22/gradle-scalatest-demo)  

In  a nutshell, the cause is from a dependency on 'org.apache.cxf:cxf-rt-frontend-jaxws:3.1.5', gradle test  will throw the exception `java.lang.IncompatibleClassChangeError: Implementing class` and `gradle test` hangs indefinitely.   
 
Any insights will be greatly appreciated. Our jdk is 1.8.121

-Chris

**Comment by kknd22** [comment]
BTW, just test on older gradle 2.10. The same issue exists as well.

**Comment by kknd22** [comment]
compile ('org.apache.cxf:cxf-rt-frontend-jaxws:3.1.9') {
        exclude group: 'org.ow2.asm', module: "asm"
}
seems to revolve this issue - reason is unknown yet

**Comment by maiflai** [comment]
Ah, yes - I have dim recollections of this on another project.

ScalaTest has an optional dependency on asm 4, but is it incompatible with asm 5?

Interestingingly https://repo1.maven.org/maven2/org/apache/cxf/cxf-parent/3.1.11/cxf-parent-3.1.11.pom suggests that CXF accepts anything from 3 to 6, so it may be a case of adding a compile dependency on asm 4?

```groovy
compile 'org.ow2.asm:asm:4.1'
```

**Comment by maiflai** [comment]
This is also backed up by an old issue on the ScalaTest mailing list: https://groups.google.com/forum/#!topic/scalatest-users/EO0KHr1CMXc

**Comment by kknd22** [comment]
I finally found the culprit:  
Since 4.0 asm has changed their group name from `asm`  to `org.ow2.asm`, which understandably messed  upgradle dependencies.    
`asm: asm: 3.3.1`  `org.ow2.asm:asm:5.0.4`  now co-exist in the classpath  
So the better fix for us is actually  upgrade org.pegdown:pegdown:1.6.0 from 1.1.0, which solve the issue cleanly.

```
\--- org.pegdown:pegdown:1.1.0
     +--- org.parboiled:parboiled-core:1.0.2
     \--- org.parboiled:parboiled-java:1.0.2
          +--- asm:asm:3.3.1
          +--- asm:asm-util:3.3.1
          |    \--- asm:asm-tree:3.3.1
          |         \--- asm:asm:3.3.1
          +--- asm:asm-tree:3.3.1 (*)
          +--- asm:asm-analysis:3.3.1
```

```
\--- org.pegdown:pegdown:1.6.0
     \--- org.parboiled:parboiled-java:1.1.7
          +--- org.parboiled:parboiled-core:1.1.7
          +--- org.ow2.asm:asm:5.0.3 -> 5.0.4
          +--- org.ow2.asm:asm-tree:5.0.3
          |    \--- org.ow2.asm:asm:5.0.3 -> 5.0.4
          +--- org.ow2.asm:asm-analysis:5.0.3
          |    \--- org.ow2.asm:asm-tree:5.0.3 (*)
          \--- org.ow2.asm:asm-util:5.0.3
               \--- org.ow2.asm:asm-tree:5.0.3 (*)

```

**Comment by maiflai** [comment]
Ah, yes - good work, picking through dependencies is never fun.

The README was written for ScalaTest 3, but in this respect it's pretty much the same so I won't update it. An older README did ask for 1.1.0.

> README.md
```groovy
dependencies {
  testCompile 'org.scalatest:scalatest_2.11:3.0.1'
  testRuntime 'org.pegdown:pegdown:1.4.2'
}
```
I seem to recall that I chose to respect the optional dependency expressed by ScalaTest but you've found that 1.6.0 is also compatible.

Upgrading to ScalaTest 2 to 3 wasn't much work when I did it last, it might be worth upgrading while it's easy?

**Comment by kknd22** [comment]
I will give it a try - BTW, 

>  optional dependency expressed by ScalaTest     


Is the the *optional* referring to  https://github.com/gradle/gradle/issues/867)?

**Comment by maiflai** [comment]
Sorry, don't think it is - that issue seems to be related to Gradle _writing_ pom files rather than reading them.

Gradle ignores the optional dependency on pegdown, which is why we then have to add it to `testRuntime`

**Comment by maiflai** [comment]
Please can this issue be closed?

Thanks,
Stu
