### ISSUE TITLE
Disable colored output

### ISSUE THREAD

**Issue by AndreyIlin** [maiflai/gradle-scalatest#49]
Currently I don't see the way how to disable colored output for tests using plugin.
There are options for runner to disable colored output: http://www.scalatest.org/user_guide/using_the_runner
This would be very helpful because Jenkins output looks like this:
<pre>
[32m- should build search parameters with a filter by archived (9 milliseconds)[0m
[32m  should build search parameters without a filter by archived[0m
[32m  - when archived is false (1 millisecond)[0m
[32m- should build search parameters with a raw query (8 milliseconds)[0m
[32m  should build search parameters without a raw query[0m
[32m  - when query is null (1 millisecond)[0m
[32m  - when query is empty (1 millisecond)[0m
</pre>
Maybe there is some workaround I can use with currently available functionality?

**Comment by maiflai** [comment]
It should respect the main Gradle command-line parameter `--console plain`?

This is covered at https://github.com/maiflai/gradle-scalatest/blob/master/src/test/groovy/com/github/maiflai/ScalaTestActionTest.groovy#L74

**Comment by AndreyIlin** [comment]
Any tip how to use this command-line parameter with gradle plugin for Jenkins?
If no, you can close this issue, I will search for that more.
Thanks a lot for the fast feedback.

**Comment by maiflai** [comment]
I imagine that you add `--console plain` to the Switches text box.

**Comment by AndreyIlin** [comment]
I will try that. Thank you very much.

**Comment by AndreyIlin** [comment]
Haven't helped. But don't want to bother you anymore. Thanks again.

**Comment by maiflai** [comment]
No worries, sorry, I'm not a Jenkins user myself
