### ISSUE TITLE
maxParallelForks not respected after gradle upgrade.

### ISSUE THREAD

**Issue by atronchi** [maiflai/gradle-scalatest#52]
Previously working config:
```
$ ./gradlew -version
Picked up _JAVA_OPTIONS: -Duser.name=mrt

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Linux 4.8.0-58-generic amd64
```

And in my build gradle:
```
classpath 'com.github.maiflai:gradle-scalatest:0.13'
...
testCompile "org.scalatest:scalatest_2.11:2.2.6"
```

After upgrading gradle this breaks:
```
$ ./gradlew -version

------------------------------------------------------------
Gradle 3.5.1
------------------------------------------------------------

Build time:   2017-06-16 14:36:27 UTC
Revision:     d4c3bb4eac74bd0a3c70a0d213709e484193e251

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Mac OS X 10.11.6 x86_64
```

In build:
```Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.StartParameter.isColorOutput() is applicable for argument types: () values: []```

**Comment by atronchi** [comment]
Following https://github.com/maiflai/gradle-scalatest/issues/37, I upgraded gradle-scalatest to 0.16:
and this seems to work fine now. :\

**Comment by atronchi** [comment]
FWIW, it would be super helpful to have a mapping of gradle-scalatest versions and known working gradle versions. Do we already have this somewhere? :)

**Comment by maiflai** [comment]
Thanks - unfortunately not, although it has been mentioned before.

There are now sufficient versions of Gradle (and of this plugin) that to maintain a full mapping would be prohibitive.

My general suggestion is that the latest version of the plugin should work with the current version of Gradle; it seems odd to upgrade to an old one?
