### ISSUE TITLE
0.17 is not in plugins.gradle.org

### ISSUE THREAD

**Issue by ahartoto** [maiflai/gradle-scalatest#55]
Hi,

It seems that 0.17 was not pushed to plugins.gradle.org.

Thanks!

**Comment by maiflai** [comment]
Yes, that's very odd, I'm using their plugin to publish and it seems to have updated the registry.

I'll have a look, sorry!

**Comment by maiflai** [comment]
I've published 0.18, which seems to have uploaded successfully. Please could you see if that works for you?

Thanks,
Stu

**Comment by maiflai** [comment]
Closing - 0.17 will not be released to the Gradle plugin registry as it has been superseded.
