### ISSUE TITLE
How to show only failed tests?

### ISSUE THREAD

**Issue by provegard** [maiflai/gradle-scalatest#66]
I'm using version 0.22.

I'd like to show only failed tests in the output from `gradle test`.

Here are things I have tried inside the `test` task:

    logging.level = LogLevel.ERROR

This resulted in no tests being shown at all. The test run failed due to failed tests though.

    testLogging {
        events "failed"
    }

This showed all tests, also the successful ones.

    testLogging {
        info.events = ["failed"]
    }

This showed all tests, also the successful ones.

    logging.level = LogLevel.ERROR
    testLogging {
        error.events = ["failed"]
    }

No tests were shown at all.

**Comment by maiflai** [comment]
I think this is a bug - the code should probably inspect the current logging level to determine the appropriate events.

Please can you try setting the overall events?
```
testLogging {
  events = ['failed']
}```

**Comment by provegard** [comment]
That worked! Odd that Gradle didn't complain syntax-wise about my first variant.

Thanks!

**Comment by maiflai** [comment]
No worries, I think the first variant is valid. I expect you can configure it such that running with `--debug` or `--info` behave differently. 

Unfortunately I've not actually tested the detailed behaviour of Gradle's native test task, I didn't have time.
