### ISSUE TITLE
filtering test cases

### ISSUE THREAD

**Issue by geoHeil** [maiflai/gradle-scalatest#71]
the documentation suggests to use:

`./gradlew test --tests MyTest`

however, this never outputs the standard out logs and never fails the test.
A `gradle test` works just fine (but is inefficient) as I cannot filter.

What is causing this strange behaviour? How can I filter tests on CLI according to some prefix but still see the logs and have them fail.

**Comment by maiflai** [comment]
What `Spec` are you using please? I've seen interesting behaviour here...

**Comment by maiflai** [comment]
I think that this doesn't work very well with tags.

In my project I've defined extra Test tasks for certain tag combinations. The command below executes all the integration tests, rather than just the intended tests.

```bash
./gradlew integrationTest --tests MyTest
```
Are you using tags here please?

**Comment by maiflai** [comment]
Closing due to lack of response.
