### ISSUE TITLE
-x test is ignored

### ISSUE THREAD

**Issue by tekumara** [maiflai/gradle-scalatest#76]
Excluding the test task is ignored, eg:
```
./gradlew -x test build
```
Will still run the tests (if the code has been changed).

**Comment by maiflai** [comment]
Sorry, I can't reproduce this.

Please could you provide a sample project (or at least the version of Gradle and this plugin that you are using)?

Thanks,
Stu.

**Comment by tekumara** [comment]
My bad, after trying to replicate this on a minimal project, the issue actually appears to be with `com.adtran.scala-multiversion-plugin`

https://github.com/ADTRAN/gradle-scala-multiversion-plugin/issues/20

**Comment by maiflai** [comment]
No worries, thanks for confirming.
