### ISSUE TITLE
Provide xmx parameter for scalatest

### ISSUE THREAD

**Issue by atais** [maiflai/gradle-scalatest#86]
Hello

I am migrating Scala project from maven to gradle. In previous configuration we had

```
<plugin>
  <groupId>org.scalatest</groupId>
  <artifactId>scalatest-maven-plugin</artifactId>
  <configuration>
    <argLine>JAVA_OPTS=Xmx=2g</argLine>
  </configuration>
</plugin>
```

and I cannot find a way to setup java opts with this wrapper.
Is it possible at all?

**Comment by maiflai** [comment]
It should respect the `Test` configuration from https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html

Have you tried the following?

```groovy
test {
  maxHeapSize = "2g"
}
```

**Comment by atais** [comment]
Wow, I did not expect configuration from the main gradle testing plugin to have impact here!
You might want to add such one-liner to the readme :-) or maybe it is just not obvious for gradle newbie, don't know.

Anyways, I have ended up using:
```
test {
        jvmArgs '-Xmx2g'
 }
```

which I think does the same and it works. Thanks a lot!
