### ISSUE TITLE
Multiple -R arguments when using testClassesDir

### ISSUE THREAD

**Issue by ben-willis** [maiflai/gradle-scalatest#89]
Hi,

I might be completely wrong here but it looks like if testClassesDir contains multiple paths then each one is added as a -R argument to the scalatest runner:
https://github.com/maiflai/gradle-scalatest/blob/master/src/main/groovy/com/github/maiflai/ScalaTestAction.groovy#L146

However according to the docs the runner can only take one -R argument:
https://scalatest.org/user_guide/using_the_runner

I guess we should be concatenating these together somehow instead?

Thanks,
Ben

Edit: Having said this, this wasn't the cause of the error I'm currently trying to debug so it might not even be an issue.

**Comment by maiflai** [comment]
Seems reasonable - 
> The -R must be followed by a space, a double quote ("), a white-space-separated list of paths and URLs, and a double quote. If specifying only one element in the runpath, you can leave off the double quotes, which only serve to combine a white-space separated list of strings into one command line argument. If you have path elements that themselves have a space in them, you must place a backslash (\) in front of the space.

I'll see what I can do to match that expectation.

**Comment by maiflai** [comment]
I've released 0.30 containing a change to address this. 

Would it be possible to close this issue please? 

Dare I ask what error you do see?

**Comment by ben-willis** [comment]
Amazing, yes I'll close this ticket :)

It's not super interesting. I was struggling with the discovery suite not picking up my tests automatically. Turned out one of my dependencies was depending on an older scalatest library and used a deprecated method. Swapping this out resolved my issue.

**Comment by maiflai** [comment]
Ah, ok - thanks for confirming, glad all's well
