### ISSUE TITLE
Equivalent of `-u build/test-reports` ?

### ISSUE THREAD

**Issue by gabrieljones** [maiflai/gradle-scalatest#90]
What is the equivalent of `-u build/test-reports` ?
https://www.scalatest.org/user_guide/using_the_runner

And how do I specify it in `build.gradle.kts`?

**Comment by maiflai** [comment]
I think that the Gradle convention is to put the XML reports into a subdirectory named for the Task itself? This is helpful when you have multiple test tasks.

You control this using the standard Test DSL. I'm not sure of the Kotlin syntax but I expect it to be very similar.
```groovy
test.reports.junitXml.destination(file('build/test-results'))
```

**Comment by gabrieljones** [comment]
How do I tell scalatest to spit out junit xml per the `-u` option?

**Comment by maiflai** [comment]
I think that's exactly what the above does?

**Comment by gabrieljones** [comment]
Ah my bad, I was confusing `build/results` with `build/test-results`
