### ISSUE TITLE
Plugin is incompatible with Gradle 7

### ISSUE THREAD

**Issue by dubinsky** [maiflai/gradle-scalatest#92]
[ScalaTestAction](https://github.com/maiflai/gradle-scalatest/blob/master/src/main/groovy/com/github/maiflai/ScalaTestAction.groovy#L69) calls [org/gradle/process/internal/DefaultExecActionFactory.root()](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecActionFactory.java#L95) with `null` for `gradleUserHome`; this is no longer supported starting with Gradle 7 ([commit with the change](https://github.com/gradle/gradle/commit/8c2f6b7db50ab071a289fb5c4cbb9b2125609105#diff-1bb630a5259160647c926dd0c3af488fedd58784fd9ab678739d03946ee7dd05)).

Also, the  method called is deprecated; the comment says:
> Do not use this. It's here because some of the services this type needs are not easily accessed in certain cases and will be removed ay some point. Use one of the other methods instead

**Comment by DanySK** [comment]
The problem seems to be here: https://github.com/maiflai/gradle-scalatest/blob/5920f79fd6e1ec5cc6793f881e23cca0ee953ac8/src/main/groovy/com/github/maiflai/ScalaTestAction.groovy#L69

**Comment by maiflai** [comment]
Yes, I'm trying to work out how to update this without having to rewrite all the tests.

**Comment by dubinsky** [comment]
> Yes, I'm trying to work out how to update this without having to rewrite all the tests.

Thank you!

**Comment by josecsotomorales** [comment]
Just got this issue when updating my project to Gradle 7.0, glad that you folks are already tracking it!

**Comment by Habitats** [comment]
Any update on this? 🙏

**Comment by maiflai** [comment]
I've uploaded 0.31 with a partial fix (it still uses a deprecated api).

Please could you take a look?

**Comment by dubinsky** [comment]
@maiflai yay! it works!!! thanks!

**Comment by josecsotomorales** [comment]
@maiflai it's working! thanks! 🚀

**Comment by dpsoft** [comment]
@maiflai works like a charm!! thanks!

**Comment by Habitats** [comment]
works like a charm indeed! 

thanks for fixing! :D

**Comment by maiflai** [comment]
thanks folks.
