### ISSUE TITLE
Version 0.31 is not properly published

### ISSUE THREAD

**Issue by chali** [maiflai/gradle-scalatest#94]
Hello, we noticed that project using dynamic version for this plugin started failing.

Declared dependency on plugin `classpath 'com.github.maiflai:gradle-scalatest:0.+'`
Project build fails with: `Plugin with id 'com.github.maiflai.scalatest' not found.`

I did a bit of searching and is likely related to the way how publishing is configured. Here are the published artifacts https://repo1.maven.org/maven2/com/github/maiflai/gradle-scalatest/0.31/ There are no jars just pom files.

I believe that after build file refactoring you are missing `from components.java`  More about it the [docs](https://docs.gradle.org/current/userguide/publishing_maven.html#sec:identity_values_in_the_generated_pom)

One unrelated note. Moving the plugin to Gradle 7 will very likely make it incompatible for existing users who are still using Gradle 6.+. Gradle 7 will use Groovy 3 for plugin compilation and classes compiled with Groovy 3 are not working with Groovy 2 in older Gradle versions. Maybe you should consider bumping a major version.

**Comment by maiflai** [comment]
Thanks - I've published the missing files, please could you check again? Sorry for the mistake.

The versions here don't follow semver as such - they are simply releases. The recent changes have been for forwards-compatibility rather than backwards.

**Comment by maiflai** [comment]
thanks, will bear that in mind.
